import { configureStore } from "@reduxjs/toolkit";
import {
	boxShadowBlurReducer,
	borderColorReducer,
	borderRadiusReducer,
	borderTypeReducer,
	borderWidthReducer,
	fontColorReducer,
	fontStyleReducer,
	fontWeightReducer,
	boxShadowHorizontalReducer,
	letterSpacingReducer,
	lineHeightReducer,
	boxShadowOpacityReducer,
	boxShadowColorReducer,
	boxShadowSpreadReducer,
	textShadowBlurReducer,
	textShadowColorReducer,
	textShadowHorizontalReducer,
	textShadowOpacityReducer,
	textTransformReducer,
	textShadowVerticalReducer,
	boxShadowVerticalReducer,
	wordSpacingReducer,
	fontSizeSliceReducer,
} from "./features";

export const store = configureStore({
	reducer: {
		borderWidth: borderWidthReducer,
		borderType: borderTypeReducer,
		borderColor: borderColorReducer,
		borderRadius: borderRadiusReducer,
		boxShadowHorizontal: boxShadowHorizontalReducer,
		boxShadowOpacity: boxShadowOpacityReducer,
		boxShadowColor: boxShadowColorReducer,
		boxShadowBlur: boxShadowBlurReducer,
		boxShadowSpread: boxShadowSpreadReducer,
		boxShadowVertical: boxShadowVerticalReducer,
		fontColor: fontColorReducer,
		fontSize: fontSizeSliceReducer,
		fontStyle: fontStyleReducer,
		fontWeight: fontWeightReducer,
		letterSpacing: letterSpacingReducer,
		lineHeight: lineHeightReducer,
		textTransform: textTransformReducer,
		wordSpacing: wordSpacingReducer,
		textShadowBlur: textShadowBlurReducer,
		textShadowColor: textShadowColorReducer,
		textShadowHorizontal: textShadowHorizontalReducer,
		textShadowOpacity: textShadowOpacityReducer,
		textShadowVertical: textShadowVerticalReducer,
	},
});
